### ISSUE TITLE
Last few lines of template are extraneous?

### ISSUE THREAD

**Issue by weisisheng** [aws-samples/sessions-with-aws-sam#8]
Fairly new to SAM but the example template for Eventbridge won't deploy for me unless I comment out these lines. Originally I thought it was the missing quote on the Description line.

  MyNotificationArn:
    Description: Topic ARN"
    Value: !Ref AWS::NotificationARNs

I don't see them referenced elsewhere and they're not in the instructional video.

Please advise. Thanks in advance.

**Comment by singledigit** [comment]
This is an output for informational only. I know you also fixed this in a PR. Thank you!
